import os
import pandas as pd
import numpy as np
from PIL import Image

def get_embryo_stem(csv_filename):
    """
    Extracts the base embryo name from the RS-FISH CSV filename.
    Handles both 'c0_N2_123_cropped_0.csv' and 'c0_N2_123_cropped_0.tif.csv'
    Returns: 'N2_123_cropped_0'
    """
    # Remove BOTH the .csv and .tif extensions if they exist
    name = csv_filename.replace('.csv', '').replace('.tif', '')
    
    # Remove the channel prefix (e.g., 'c0_', 'c1_', 'c2_')
    if name.startswith('c0_') or name.startswith('c1_') or name.startswith('c2_'):
        name = name[3:]
        
    return name

def run_filter_localizations(localization_folder, mask_folder, output_folder):
    """
    Filters raw RS-FISH CSV localizations using 2D binary StarDist masks.
    Only spots falling inside the mask (value > 0) are kept.
    """
    os.makedirs(output_folder, exist_ok=True)

    print(f"Scanning for CSVs in: {localization_folder}")
    csv_files = [f for f in os.listdir(localization_folder) if f.endswith('.csv')]
    print(f"Found {len(csv_files)} RS-FISH localization files.\n")

    processed_count = 0
    empty_count = 0
    error_count = 0

    for csv_filename in csv_files:
        csv_path = os.path.join(localization_folder, csv_filename)
        stem = get_embryo_stem(csv_filename)
        
        # The mask generated by the previous pipeline step usually looks like this:
        mask_filename = f"{stem}.mask.tif"
        mask_path = os.path.join(mask_folder, mask_filename)
        
        # Fallback check just in case the mask is named slightly differently
        if not os.path.exists(mask_path):
            mask_filename = f"{stem}.tif"
            mask_path = os.path.join(mask_folder, mask_filename)
            
        if not os.path.exists(mask_path):
            print(f"⚠️ Warning: No matching mask found for {csv_filename} (Looked for {mask_filename})")
            error_count += 1
            continue
            
        try:
            # 1. Load the Mask
            mask_image = Image.open(mask_path)
            mask_array = np.array(mask_image) > 0  # Creates a True/False boolean array
            mask_h, mask_w = mask_array.shape
            
            # 2. Load the Localizations
            if os.path.getsize(csv_path) == 0:
                pd.DataFrame(columns=['x', 'y']).to_csv(os.path.join(output_folder, csv_filename), index=False)
                empty_count += 1
                continue
                
            localizations = pd.read_csv(csv_path)
            
            if len(localizations) == 0 or 'x' not in localizations.columns or 'y' not in localizations.columns:
                localizations.to_csv(os.path.join(output_folder, csv_filename), index=False)
                empty_count += 1
                continue
                
            # 3. Fast Vectorized Filtering
            x_coords = localizations['x'].round().astype(int).clip(0, mask_w - 1)
            y_coords = localizations['y'].round().astype(int).clip(0, mask_h - 1)
            
            valid_spots_mask = mask_array[y_coords, x_coords]
            filtered_localizations = localizations[valid_spots_mask].copy()
            
            # 4. Save
            out_path = os.path.join(output_folder, csv_filename)
            filtered_localizations.to_csv(out_path, index=False)
            
            processed_count += 1
            
            if processed_count % 500 == 0:
                print(f"Processed {processed_count} files...")
                
        except Exception as e:
            print(f"❌ Error processing {csv_filename}: {e}")
            error_count += 1

    print("\n==========================================")
    print("✅ MASK FILTERING COMPLETE")
    print("==========================================")
    print(f"Successfully filtered: {processed_count} files")
    print(f"Empty/No Spots found : {empty_count} files")
    print(f"Errors/Missing Masks : {error_count} files")
    print(f"Outputs saved to     : {output_folder}")